# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql

    url: jdbc:mysql://localhost:3306/finaldb?useSSL=false&serverTimeZone=UTC
    username: root
    password: Oliver88$
