# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  jwt:
    header: Authorization
    secret: my-very-secret-key
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/finaldb?useSSL=false&serverTimeZone=UTC
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}

