# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  jwt:
    secret: my-secret-key
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    #    url: jdbc:mysql://${DB_MYSQL_DESAENV04_PROYFINAL_PROYFINAL_ENDPOINT}/proyfinal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    # host: localhost:3306
    # db: proyectofinal_db
    # username: final
    # password: final
    host: localhost:3306
    db: finaldb
    platform: mysql

    #url: jdbc:mysql://localhost:3306/finaldb?useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
    initialization-mode: always

    server:
      port: 8082 # no cambiar en prod
