# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/finaldb?useSSL=false&serverTimeZone=UTC
    username: root
    password: Oliver88$
    #url: jdbc:mysql://proxysql.master.meliseginf.com:6612/finaldb1?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    #username: ${LOCAL_DB_USER}
    #password: ${LOCAL_DB_PASS}